name: Sync LeetCode Submissions

on:
  workflow_dispatch: # Run manually anytime
  schedule:
    - cron: '0 0 * * *' # Automatically runs every night to fetch new submissions

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions  # <--- ALL past and future solutions go here!
          verbose: true
